Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using ETC.BL;
using ETC.BL.Purchase;
using ETC.Structures.Models;
using Newtonsoft.Json;
using WebEducaStore.Models;
using WebEducaStore.Services;
using WebEducaStore.ViewModels;

namespace WebEducaStore.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private WebEducaStoreEntities db = new WebEducaStoreEntities();

        //
        // GET: /Cart/
        [Authorize]
        public ActionResult Index(int userId = 0)
        {
            PersonSession person = (PersonSession)Session["Person"];

            //Instantiate the classes for server data
            CartBL cartBL = new CartBL();
            ServCart servCart = new ServCart(ref db);
            ServCatalog servCatalog = new ServCatalog(ref db);
            //Instantiate the viewmodel
            CartListVM cartVM = new CartListVM();

            /*
            * get all the products for the person carts
            * with all the pricing information related
            * (only check for the discount added with the product
            * to the cart and only assign if valid)
            * */
            List<CarthasProduct> carthasProducts = cartBL.GetCartsProductsWithPricingForPerson((long)person.Id, ConfigurationManager.AppSettings["STOREFRONT_EDUCASTORE"], ConfigurationManager.AppSettings["STOREFRONT_EDUCADESK"]);

            //load the cart viewmodel
            cartVM = servCart.getCartForVm(carthasProducts);

            //load all the catalogs for the institution
            //contentVM.Catalogs = servCatalog.getCatalogsForVM(person.roleInstitutionId);
            //var catalogs = servCatalog.getCatalogsForVM(43);

            //validate if it has items
            //load the contents if applies
            cartVM.Content = servCart.getCartContentsForVm(carthasProducts, Convert.ToInt32(person.Id));

            //load the colors for distinct catalogs id
            //cartVM.catalogColors = servCart.getDistinctCatalogColorsForVm(cartVM);

            //need the person information for ids
            cartVM.person = person;

            return View(cartVM);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmptyCart(int idCart)
        {
            PersonSession person = (PersonSession)Session["Person"];

            CartBL cartBL = new CartBL();

            var storefront = ConfigurationManager.AppSettings["STOREFRONT_EDUCASTORE"];

            cartBL.EmptyCarts((int)person.Id, storefront);

            return RedirectToAction("Index", new { });
        }

        [Authorize]
        [HttpPost]
        public ActionResult CheckoutConfirmed(int idCart)
        {
            PersonSession person = (PersonSession)Session["Person"];

            //Instantiate the classes for server data
            ServCart servCart = new ServCart(ref db);
            ServCheckout servCheckout = new ServCheckout(ref db);
            CartBL cartBL = new CartBL();

            Utility utils = new Utility(ref db);

            //load the cart
            /*
            * get all the products for the person carts
            * with all the pricing information related
            * (only check for the discount added with the product
            * to the cart and only assign if valid)
            * */
            List<CarthasProduct> carthasProducts = cartBL.GetCartsProductsWithPricingForPerson((long)person.Id, ConfigurationManager.AppSettings["STOREFRONT_EDUCASTORE"], ConfigurationManager.AppSettings["STOREFRONT_EDUCADESK"]);

            List<ContentVM> products = servCart.getCartContentsForVm(carthasProducts, (int)person.Id);
            //var productsInOrders = purchaseBL.GetListIdProductsInOrders((int) person.Id);

            /*
             * Validate if items is already bought
             * */
            //if (!productsInOrders.Intersect(carthasProducts.Select(w=>w.ProductID).ToList()).Any())
            if (!products.Any(w => w.alreadyBought))
            {
                //Check each content and add to a specified list of content
                //depending of the price
                List<ContentVM> productsWithPrice = new List<ContentVM>();
                List<ContentVM> productsWithoutPrice = new List<ContentVM>();
                foreach (var product in products)
                {
                    if (product.pricing != null && product.pricing.FinalAmount == 0)
                    {
                        productsWithoutPrice.Add(product);
                    }
                    else
                    {
                        productsWithPrice.Add(product);
                    }
                }

                /*
                 * Call the web services to place the order
                 * If there are items with price and without price, place two different orders
                 * Otherwise, place one order
                 * */
                //items without price
                bool contentsWithoutPriceJson = false;
                if (productsWithoutPrice.Count != 0)
                {
                    //build the object for the post rest WS
                    SetUserETC userEtc = servCheckout.buildObjForWsNoPrice(person, productsWithoutPrice);

                    /*
                     * Call the web service and obtain the json result into
                     * the corresponding object
                     * */
                    string json = utils.postJsonWs(userEtc, ConfigurationManager.AppSettings["WS_HOST"] +
                        ConfigurationManager.AppSettings["WS_ETC_SETORDERBYUSER"]);

                    //string json = null;

                    if (!String.IsNullOrEmpty(json))
                    {
                        //deserialize the json returned into the response object
                        ResponseUser response = JsonConvert.DeserializeObject<ResponseUser>(json);
                        if (response.users.FirstOrDefault().errorcode == 0)
                        {
                            contentsWithoutPriceJson = true;
                        }
                    }
                }

                //items with price
                bool contentsWithPriceJson = false;
                if (productsWithPrice.Count != 0)
                {
                    //build the object for the post rest WS
                    SetUserETC userEtc = servCheckout.buildObjForWsWithPrice(person, productsWithPrice);

                    /*
                     * Call the web service and obtain the json result into
                     * the corresponding object
                     * */
                    string json = utils.postJsonWs(userEtc, ConfigurationManager.AppSettings["WS_HOST"] + 
                        ConfigurationManager.AppSettings["WS_STUDENTS_SETORDERUSER"]);

                    if (!String.IsNullOrEmpty(json))
                    {
                        //deserialize the json returned into the response object
                        ResponseUser response = JsonConvert.DeserializeObject<ResponseUser>(json);
                        if (response.users.FirstOrDefault().errorcode == 0)
                        {
                            contentsWithPriceJson = true;
                        }
                    }
                }

                /*
                 * If the orders were created successfuly (at least one of two possible),
                 * load checkout viewmodel, empty cart and render a new view
                 * */
                if (contentsWithPriceJson || contentsWithoutPriceJson)
                {
                    /*
                    * Load ViewModel to show acquired items
                    * */
                    //Instantiate the viewmodel
                    CheckoutVM checkoutVM = new CheckoutVM();
                    //set the corresponding contents to the VM
                    checkoutVM.contentWithoutPrice = productsWithoutPrice;
                    checkoutVM.contentWithPrice = productsWithPrice;
                    //set the statuses of contents
                    checkoutVM.contentWithPriceSuccess = contentsWithPriceJson;
                    checkoutVM.contentWithoutPriceSuccess = contentsWithoutPriceJson;

                    /*
                     * Empty Cart
                     * */
                    var storefront = ConfigurationManager.AppSettings["STOREFRONT_EDUCASTORE"];

                    cartBL.EmptyCarts((int)person.Id, storefront);

                    return View("CheckoutSummary", checkoutVM);
                }
                else
                {
                    /*
                     * Error creating order, pay, petition, etc
                     * */
                    //Instantiate the viewmodel
                    CartListVM cartVM = new CartListVM();

                    //load the cart viewmodel
                    cartVM = servCart.getCartForVm(carthasProducts);

                    //load all the catalogs for the institution
                    //contentVM.Catalogs = servCatalog.getCatalogsForVM(person.roleInstitutionId);
                    //var catalogs = servCatalog.getCatalogsForVM(43);

                    //validate if it has items
                    //load the contents if applies
                    cartVM.Content = servCart.getCartContentsForVm(carthasProducts, Convert.ToInt32(person.Id));

                    //put the error of content already bought
                    cartVM.errorMessage = "Ocurrió un problema al generar la orden, contacte al administrador.";

                    cartVM.person = person;

                    return View("Index", cartVM);
                }
            }
            else
            {
                //Instantiate the viewmodel
                CartListVM cartVM = new CartListVM();

                //load the cart viewmodel

Views/Cart/CheckoutSummary.cshtml
@model WebEducaStore.ViewModels.CheckoutVM

@{
  ViewBag.Title = "CheckoutSum";
}


@*List free contents, indicating if they order were successfuly or not*@
@{
  if(Model.contentWithoutPriceSuccess)
  {
  <div class="block">
    <div class="block-title">
      <h4 class="text-success">Productos satisfactoriamente adquiridos disponibles para su uso:</h4>
    </div>
    <div class="block-content full">
      @Html.Partial("_listOrderedItems", Model.contentWithoutPrice)
    </div>
  </div>
  }
  else
  {
  <div class="block">
    <div class="block-title">
      <h4 class="text-warning">No fue posible procesar los siguientes productos:</h4>
    </div>
    <div class="block-content full">
      @Html.Partial("_listOrderedItems", Model.contentWithoutPrice)
    </div>
  </div>
  }
}


<br />
<a href="@Url.Action("ListProducts", "Content", new { })"><i class="glyphicon-unshare text-info"></i>&nbsp;Volver a la tienda</a>

Views/Cart/Index.cshtml
@model WebEducaStore.ViewModels.CartListVM

@{
	ViewBag.Title = "Carrito";
	ViewBag.MainHeader = "Carrito de compras";
	ViewBag.MainIcon = "glyphicon-shopping_cart themed-color";
}

<!-- div to replace with message from ajax -->
<div id="alertMessage">
	@{
		if (Model.errorMessage != null)
		{
		<div class="@Model.errorClass">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			@Model.errorMessage
		</div>
		}
	}
</div>

@{
	if (!Model.Content.Any())
	{
	@:<h4 class="sub-header">No posee contenidos en el carrito de compras. <a href="@Url.Action("ListProducts", "Content")">Le sugerimos ir a la lista de contenidos.</a></h4>
	}
	else
	{
		<a href="@Url.Action("ListProducts", "Content")" class="btn"><i class="icon-angle-right"></i>&nbsp;Ir a catalogo</a>
		<!-- Table -->
		<div>
			<div style="width: 74%;display: inline-block;">
				<table class="table table-borderless table-hover">
					<thead>
						<tr>
							<th class="span1 text-center"><i class="icon-bolt"></i></th>
							<th class="text-center"><i class="icon-picture"></i></th>
							<th class="span6"><i class="icon-tag"></i>&nbsp;Contenido</th>
							<th class="span2">Editorial</th>
							<th class="span2">Estado</th>
							<th class="span1 text-center">Cant</th>
							<th class="text-right">Precio</th>
						</tr>
					</thead>
					<tbody>
						@Html.Partial("_listCartItems", Model)
					</tbody>
				</table>
			</div>
			<div class="pull-right"style="display: inline-block;height: 136px;vertical-align: top;width: 23%;">
				<a href="#modal-emptycart" data-toggle="modal" id="emptycart_link" class="btn btn-danger pull-right" title="Vaciar carrito" style="margin-bottom: 10px;"><i class="icon-remove"></i>&nbsp;Vaciar el carrito</a>
				<table class="table" style="margin: 0" >
					<tbody >
						<tr class="info" style="border-top-width: 4px;border-top-style: solid;border-top-color: lightgray;border-bottom-width: 4px;border-bottom-style: solid;border-bottom-color: lightgray;">
							<td class="span2 text-center" style="background-color: lightgray;">
								<span class="text-black"><b>Sub total</b></span>
							</td>
							<td class="span2 text-center" style="border-left-style: solid;border-left-width: 1px;border-left-color: black;background-color: lightgray;">
								<span class="text-black"><b>@Model.currency</b></span>
							</td>
							<td class="span3 text-right" style="border-left-style: solid;border-left-width: 1px;border-left-color: black;background-color: lightgray;">
								<span class="text-black" ><b>@ViewHelpers.SetQuantityOuput(Convert.ToDecimal(Model.Content.Sum(w => w.pricing.SubTotalAmount)))</b></span>
							</td>
						</tr>
						@if(Model.tax != null && Model.tax != 0)
						{
							<tr class="info" style="border-top-width: 4px;border-top-style: solid;border-top-color: lightgray;border-bottom-width: 4px;border-bottom-style: solid;border-bottom-color: lightgray;">
								<td class="span2 text-center" style="background-color: lightgray;">
									<span class="text-black"><b>Impuesto</b></span>
								</td>
								<td class="span2 text-center" style="border-left-style: solid;border-left-width: 1px;border-left-color: black;background-color: lightgray;">
									<span class="text-black"><b> @Model.currency </b></span>
								</td>
								<td class="span3 text-right" style="border-left-style: solid;border-left-width: 1px;border-left-color: black;background-color: lightgray;">
									<span class="text-black"><b>@ViewHelpers.SetQuantityOuput(Convert.ToDecimal(Model.Content.Sum(w => w.pricing.TaxAmount)))</b></span>
								</td>
							</tr>
						}
						<tr class="success" style="border-top-width: 4px;border-top-style: solid;border-top-color: gray;border-bottom-width: 4px;border-bottom-style: solid;border-bottom-color: gray;">
							<td class="span2 text-center" style="background-color: gray;">
								<span class="text-black"><b>Total</b></span>
							</td>
							<td class="span2 text-center" style="border-left-style: solid;border-left-width: 1px;border-left-color: black;background-color: gray;">
								<span class="text-black"><b>@Model.currency</b></span>
							</td>
							<td class="span3 text-right" style="border-left-style: solid;border-left-width: 1px;border-left-color: black;background-color: gray;">
								<span class="text-black"><b>@ViewHelpers.SetQuantityOuput(Convert.ToDecimal(Model.Content.Sum(w => w.pricing.FinalAmount)))</b></span>
							</td>
						</tr>
					</tbody>
				</table>
				<div class="clearfix" style="margin-top: 8px;">
					<div class="pull-right">
						<a href="#modal-checkout" data-toggle="modal" id="checkout_link" class="btn btn-success" title="Comprar" style="width: 113px;"><i class="icon-ok"></i>&nbsp;Comprar</a>
					</div>
				</div>
			</div>
		</div>
	}
}

<!-- Regular Modal -->
<div id="modal-emptycart" class="modal hide fade">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">X</button>
		<h4>Vaciar carrito</h4>
	</div>
	<div class="modal-body">
		<p>
			¿Está seguro que desea vaciar el carrito?
      <br />
			<i>Esto quitará a todos los contenidos del carrito</i>
		</p>
	</div>
	<div class="alert"><i class="glyphicon-warning_sign"></i>&nbsp;Esta acción es irreversible.</div>
	<div class="modal-footer">
		@using (Html.BeginForm("EmptyCart", "Cart", FormMethod.Post))
		{
			@Html.AntiForgeryToken()
			@Html.Hidden("idCart", Model.cartId)
			<button class="btn btn-danger" data-dismiss="modal">Cancelar</button>      
			<button type="submit" class="btn btn-success">Vaciar</button>
		}
	</div>
</div>
<!-- END Regular Modal -->

<!-- Regular Modal -->
<div id="modal-checkout" class="modal hide fade">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">X</button>
		<h4>Orden de compra</h4>
	</div>
	<div class="modal-body">
		<p>
			¿Está seguro que desea colocar la orden de compra por un total de <b>@Model.currency @ViewHelpers.SetQuantityOuput(Convert.ToDecimal(Model.Content.Sum(w => w.pricing.FinalAmount)))</b>?
      <br />
			<br />
			<i>Puede regresar y revisar la orden antes de confirmar</i>
		</p>
	</div>
	<div class="alert"><i class="glyphicon-warning_sign"></i>&nbsp;Esta acción es irreversible.</div>
	<div class="modal-footer">
		@using (Html.BeginForm("CheckoutConfirmed", "Cart", FormMethod.Post, new { id = "checkout_form"}))
  {
			@Html.AntiForgeryToken()
			@Html.Hidden("idCart", Model.cartId)
			<button class="btn btn-danger" data-dismiss="modal"><b>Volver</b></button>      
			<button type="submit" class="btn btn-success"><b>Confirmar</b></button>
  }
	</div>
</div>
<!-- END Regular Modal -->

@section Scripts {
	<script>

        // prevent mutiple click when submitting an order
	    $(function() { //shorthand document.ready function
	        $('#checkout_form').on('submit', function(e) { //use on if jQuery 1.7+
	            //e.preventDefault();  //prevent form from submitting
	            $("#checkout_form :button").unbind('click').attr('disabled', 'disabled');
	        });
	    });


    @*function to treat simple link as submit button*@
		$(function () {
			$('#emptycart_link').click(function () {
				$('form#EmptyCartForm').submit();
			});
		});

		function removeItem(idProduct, idCart) {

			$.ajax({
				type: 'POST',
				//url: 'RemoveFromCart',
				url: '@Url.Action("RemoveFromCart", "Cart")',
        data: { idProduct: idProduct, idCart: idCart },
        success: function (result) {
        	if (result.wasRemoved) {
        		//if there is no items left in the cart, redirect to the same page
        		if (result.cartListVm.numberItems == 0) {
        			var url = '@Url.Action("Index", "Cart", new { })';
            	var personId = @Convert.ToInt32(Model.person.Id);
            	window.location.href = url.replace('__id__', personId);
            }

          	//removes the row
			$("#itemrow-" + idProduct).fadeOut('slow');
          	//updates the cart info
			$('#cart-subtotal').text(result.cartListVm.currency + " " + result.cartListVm.subtotal);
			$('#cart-tax').text(result.cartListVm.currency + " " + result.cartListVm.tax);
			$('#cart-total').text(result.cartListVm.currency + " " + result.cartListVm.total);

          	//$("#alertMessage").removeData();
			$("#alertMessage").replaceWith(result.alertMessage);
		}
		else {
          	//shows the error message that was returned because
			$("#alertMessage").replaceWith(result.alertMessage);
		}

        	//DEPRECATED - to change specific attributes of the html
        	//$('#imagecart-26').attr('src', '/Images/DonQuijote.jpg');
        	//$('#imagecart-26').attr('title', 'Ya ha sido añadido al carrito.');
        },
      	error: function () {
      		alert("Ha ocurrido un error, contacte al administrador");
      	}
      });
}

	</script>
}

Views/Cart/_listCartItems.cshtml
@using WebEducaStore.Utils
@model WebEducaStore.ViewModels.CartListVM

@for(int i = 0; i < Model.Content.Count; i++)
{
  string htmlTableRow = "itemrow-" + @Model.Content[i].id;
  <tr id="@htmlTableRow">
      <td class="span1 text-center">
          <a href="javascript:removeItem(@Model.Content[i].id, @Model.cartId)" @*data-toggle="tooltip"*@ title="Quitar producto">
              <img src="~/Images/removefromcart.png" />
          </a>
      </td>
      <td class="text-center" style="padding: 3px 2px;margin: auto auto">
      @if (Utility.VerifyImage(Model.Content[i].image_path))
          {
              <!-- Just a link with the href of the large image and a data-toggle attribute with the value lightbox-image -->
              <a href="@Model.Content[i].image_path" data-toggle="lightbox-image">
                  <img src="@Model.Content[i].image_path" width="64" height="64" class="media-object img-rounded pull-left" alt="Image" style="max-width: 64px; max-height: 64px">
              </a>
          }
          else
          {
              <img src="~/Images/educatablet_header.png" width="64" height="64" class="media-object img-rounded pull-left" alt="Image" style="max-width: 64px; max-height: 64px">
              }
          </td>
        <td class="span6">
            <strong>@Model.Content[i].title</strong><br>
        @*Publicada su primera parte con el título de El ingenioso hidalgo don Quijote de la Mancha a comienzos de 1605, es una de las obras más des...<br>*@
        <em>@Model.Content[i].author</em><br>

                                        @*     @foreach(var catalog in Model.Content[i].Catalogs)
    {
    string stringColor = @Model.catalogColors[catalog.ID_CATALOG];
    <span class="badge" style="background-color:@stringColor">@catalog.DESCRIPCION</span>
    }
    *@

        </td>
      <td class="span2">@Model.Content[i].publisher</td>
    <td class="span2">
      @if(Model.Content[i].alreadyBought)
      {
        <span class="label label-important"><i class="icon-warning-sign"></i>&nbsp;¡Ya adquirido!</span>
      }
      else
      {
        <span class="label label-success"><i class="icon-ok"></i>&nbsp;Disponible</span>
      }
    </td>
    <td class="span1 text-center">
      @Model.Content[i].quantity
    </td>
    <td class="text-right">
      <span class="text-black">@ViewHelpers.SetQuantityOuput(Convert.ToDecimal(Model.Content[i].pricing.FinalAmount))</span>
    </td>
  </tr>
}

Views/Cart/_listOrderedItems.cshtml
@model List<WebEducaStore.ViewModels.ContentVM>

<ul class="icons-ul list">
  @foreach(var content in Model)
  {
    <li>
      <i class="icon-li icon-book"></i>@content.title
      <ul class="icons-ul">
        @if(!String.IsNullOrEmpty(content.author))
        {
          <li><i class="icon-li icon-ok"></i><b>Autor:</b> @content.author</li>
        }
        @if(!String.IsNullOrEmpty(content.publisher))
        {
          <li><i class="icon-li icon-ok"></i><b>Editorial:</b> @content.publisher</li>
        }
      </ul>
    </li>
  }
</ul>